DA_SERVER_URL: opcda://localhost/Matrikon.OPC.Simulation.1
HDA_SERVER_URL: opchda://localhost/Matrikon.OPC.Simulation.1
ITEM_PER_SUBSCRIBER: 50
SAMPLE_RATE: 1000
INFLUXDB_URL: URL
INFLUXDB_TOKEN: TOKEN
INFLUXDB_BUCKET: BUCKET
INFLUXDB_MONITOR_BUCKET: BUCKET
INFLUXDB_ORG: ORG