UA_SERVER_URL: opc.tcp://localhost:4840/opcua
ITEM_PER_SUBSCRIBER: 1
SAMPLE_RATE: 1000
FLUSH_RATE: 5000
INFLUXDB_URL: URL
INFLUXDB_TOKEN: TOKEN
INFLUXDB_BUCKET: BUCKET
INFLUXDB_MONITOR_BUCKET: BUCKET
