UA_SERVER_URL: opc.tcp://localhost:4840/freeopcua/server
#UA_SERVER_URL: opc.tcp://10.4.4.88:6100
ITEM_PER_SUBSCRIBER: 100
SAMPLE_RATE: 1000
FLUSH_RATE: 5000
INFLUXDB_URL: http://10.40.40.49:8086
INFLUXDB_TOKEN: BdvYrs7_TnPoICMsGU1AlPvoWc1BgPIZG_9578Vm-SAnEiR4qtnizzzP8sSMI4I0SVFBbFR8EzJEL_opkgoypA==
INFLUXDB_BUCKET: datahub-test
INFLUXDB_MONITOR_BUCKET: monitoring
INFLUXDB_ORG: BDPOC
